### PR TITLE
Fixed mavigation look and feel on mobile devices 

### PR DESCRIPTION
**Pull request by frankremmy**
I fixed issue #24

### CODE REVIEW

**Comment by dwjohnston** [comment]
Tested this on my machine and it looks good. You possible want to remove that .vscode config file though.

**Comment by frankremmy** [comment]
Okay @dwjohnston. Will do that now.

**Comment by emmalearnscode** [comment]
Please resubmit the PR when you've removed your VS Code config file and I will then merge @frankremmy

**Comment by frankremmy** [comment]
@emmalearnscode I've removed the config file.

**Comment by emmalearnscode** [comment]
Thanks for your contribution!

**Pull request merged**
