### PR TITLE
adding my experience into HF2020 - amoghrajesh

### PR DESCRIPTION
**Pull request by amoghrajesh**

### CODE REVIEW

**Comment by emmalearnscode** [comment]
Thanks for your contribution!

**Comment by amoghrajesh** [comment]
Hey @emmalearnscode , does the PR need to have hactoberfest-accepted label or just merging is sufficient for it to count?

**Comment by emmalearnscode** [comment]
I think just merging it counts but I'll add the label too just incase (I keep forgetting to add it when I merge so good job you asked!)

**Comment by amoghrajesh** [comment]
Thanks a lot!

**Pull request merged**
